# ====== CONFIGURACIÓN DOTENV (BUSCA EL .env EN LA RAÍZ) ======
springdotenv.directory=./
springdotenv.filename=.env
springdotenv.ignoreIfMissing=false
springdotenv.systemProperties=true
springdotenv.exportToSystemProperties=true

# ====== BASE DE DATOS (Lee del .env) ======
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# ====== JWT (Lee del .env) ======
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION}

# ====== CORREO (Lee del .env) ======
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# ====== RUTA DE ARCHIVOS ======
app.features.file-path=./config/features.json
app.features.admin-logs-enabled=true