spring.application.name=travel-backend

# Configuración de Conexión Local
spring.datasource.url=jdbc:mysql://localhost:3306/tallerlocal?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# Dialecto y JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# 'update' creará las tablas nuevas (como favorites y reviews) automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update

# Mostrar el SQL en consola (Muy útil para debuguear los Triggers que hicimos)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración de Pool (En local puedes subirlo un poco si quieres)
spring.datasource.hikari.maximum-pool-size=5

app.jwt.secret=ClaveSecretaParaLaFirmaDelToken2026
app.jwt.expiration=86400000