# Perfil activo por defecto
spring.profiles.active=dev
spring.application.name=travel-backend

# ====== JPA / HIBERNATE ======
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ====== LOGS ======
logging.file.name=logs/app.log
logging.level.root=INFO 
logging.level.com.traveling.travel_backend=INFO
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# ====== CONFIGURACIONES DE CORREO (COMUNES) ======
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ====== URL FRONTEND (Apunta a la variable) ======
app.frontend.url=${FRONTEND_URL} 