<<<<<<< HEAD
# ====== INYECCIÓN DESDE EL SERVIDOR DE PRODUCCIÓN ======
=======
# ====== BASE DE DATOS ======
>>>>>>> adac081e57ca2d21907851e706198c0408c180fe
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# En producción es mejor no usar "update" por seguridad
spring.jpa.hibernate.ddl-auto=validate

# ====== JWT ======
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION}

<<<<<<< HEAD
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# ====== CONFIGURACIONES DE PRODUCCIÓN ======
spring.jpa.hibernate.ddl-auto=validate
app.features.file-path=/app/config/features.json
app.features.admin-logs-enabled=false

# ====== SWAGGER DESACTIVADO EN PRODUCCIÓN ======
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false
=======
# ====== CORREO ======
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# ====== RUTA DE ARCHIVOS EN PRODUCCIÓN ======
app.features.file-path=/app/config/features.json
app.features.admin-logs-enabled=false
>>>>>>> adac081e57ca2d21907851e706198c0408c180fe
