# dotenv
springdotenv.directory=.
springdotenv.filename=.env
springdotenv.ignoreIfMissing=false
springdotenv.systemProperties=true
springdotenv.exportToSystemProperties=true

# Base de datos (toma valores del .env)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION}

# Mostrar SQL
spring.jpa.show-sql=true