<<<<<<< HEAD
# ====== DOTENV (Busca el .env en la raíz) ======
=======
# ====== CONFIGURACIÓN DOTENV (BUSCA EL .env EN LA RAÍZ) ======
>>>>>>> adac081e57ca2d21907851e706198c0408c180fe
springdotenv.directory=./
springdotenv.filename=.env
springdotenv.ignoreIfMissing=false
springdotenv.systemProperties=true
springdotenv.exportToSystemProperties=true

<<<<<<< HEAD
# ====== INYECCIÓN DESDE EL .env ======
=======
# ====== BASE DE DATOS (Lee del .env) ======
>>>>>>> adac081e57ca2d21907851e706198c0408c180fe
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

<<<<<<< HEAD
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION}

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# ====== CONFIGURACIONES LOCALES ======
app.features.file-path=./config/features.json
app.features.admin-logs-enabled=true

# ====== SWAGGER ACTIVO EN DESARROLLO ======
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
=======
# ====== JWT (Lee del .env) ======
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION}

# ====== CORREO (Lee del .env) ======
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# ====== RUTA DE ARCHIVOS ======
app.features.file-path=./config/features.json
app.features.admin-logs-enabled=true
>>>>>>> adac081e57ca2d21907851e706198c0408c180fe
