# ====== INYECCIÓN DESDE EL SERVIDOR DE PRODUCCIÓN ======
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION}

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# ====== CONFIGURACIONES DE PRODUCCIÓN ======
spring.jpa.hibernate.ddl-auto=validate
app.features.file-path=/app/config/features.json
app.features.admin-logs-enabled=false

# ====== SWAGGER DESACTIVADO EN PRODUCCIÓN ======
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false