# Perfil activo por defecto
spring.profiles.active=dev
spring.application.name=travel-backend

<<<<<<< HEAD
# ====== JPA ======
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# LIMITAR CONEXIONES (Solución al error FATAL de Supabase)
spring.datasource.hikari.maximum-pool-size=4

=======
# ====== JPA / HIBERNATE ======
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

>>>>>>> adac081e57ca2d21907851e706198c0408c180fe
# ====== LOGS ======
logging.file.name=logs/app.log
logging.level.root=INFO 
logging.level.com.traveling.travel_backend=INFO
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

<<<<<<< HEAD
# ====== EMAIL (CONFIGURACIÓN GENERAL) ======
=======
# ====== CONFIGURACIONES DE CORREO (COMUNES) ======
>>>>>>> adac081e57ca2d21907851e706198c0408c180fe
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

<<<<<<< HEAD
# ====== FRONTEND URL ======
app.frontend.url=${FRONTEND_URL}
=======
# ====== URL FRONTEND (Apunta a la variable) ======
app.frontend.url=${FRONTEND_URL} 
>>>>>>> adac081e57ca2d21907851e706198c0408c180fe
